name: "Publish new release"

on:
  push:
    branches:
      - 'staging'
      - 'trying'
      - 'master'
      - 'dev'
  pull_request:

jobs:
  create_docker_image:
    name: Create and publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: work
        run: |
          VERSION="${{ steps.extract-version.outputs.version }}"
          echo "::starting docker-container comitnetwork/cnd:$VERSION"
          docker run --publish 8000:8000 --detach --name cnd_container comitnetwork/cnd
          curl --fail localhost:8000/
          echo "::cnd API curled successfully"
          docker stop cnd_container
      - name: fail
        run: |
          VERSION="${{ steps.extract-version.outputs.version }}"
          echo "::starting docker-container comitnetwork/cnd:$VERSION"
          docker run --publish 8000:8000 --detach --name cnd_container2 comitnetwork/cnd
          curl --fail localhost:8001/
          echo "::cnd API curled successfully"
          docker stop cnd_container
